title: Arsa emuārs
description: ''
baseurl: ''
url: 'http://raksti.arseniuss.id.lv'
twitter_username: AArseniussS
github_username:  arseniuss

markdown: kramdown

permalink: '/:year/:month/:day/:title.html'

plugins: 
    - jekyll-paginate
    - jekyll-archives

exclude:
    - script.sh

paginate: 10
jekyll-archives:
  enabled: all
  layouts:
      year: year-archive
      month: month-archive
      day: day-archive
      tag: tag-archive-layout
  permalinks:
    year: '/a/:year/'
    month: '/a/:year/:month/'
    day: '/a/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
